Algoritmo "Par ou ímpar"

Var

   // Seção de Declarações das variáveis
   numerodigitado: inteiro
   valorlogico: logico

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Digite um número e iremos identificar se é par ou ímpar: ")
   leia(numerodigitado)

   valorlogico <- numerodigitado%2=0

   escreval("O numero ", numerodigitado, " é par ? ", valorlogico )

Fimalgoritmo