Algoritmo "Graus"

Var

   // Seção de Declarações das variáveis
   graus_fahrenheit: real
   graus_celcius: real

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Digite o valor da temperatura em fihrenheit gostaria de converter: ")
   leia(graus_fahrenheit)

   graus_celcius <- (graus_fahrenheit - 32) * 5/9

   escreva("A temperatura em celcius é ", graus_celcius)


Fimalgoritmo