Algoritmo "Exibição"

Var

   // Seção de Declarações das variáveis
   n: inteiro
   resultado01: inteiro
   resultado02: inteiro

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o primeiro número: ")
   leia(n)

   resultado01 <- n - 1
   resultado02 <- n + 1

   escreval("O antecessor do número é", resultado01)
   escreva("O sucessor do número é", resultado02)


Fimalgoritmo