Algoritmo "Numero Aleatório"

Var

   // Seção de Declarações das variáveis
   numeroaleatorio: inteiro
   numero: inteiro

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...

   numeroaleatorio <- RandI(50)

   escreval("Digite um numero aleatoriamentee confirme se acertou: ")
   leia(numero)

   escreval("O chute ", numero , " é igual a ", numeroaleatorio = numero)

Fimalgoritmo